/**
 * categories.mjs — Refined topic categorization for Claude Projects
 *
 * 15 topic buckets with weighted keyword matching.
 * Title matches weighted 3x, body matches 1x.
 * Minimum score threshold of 2 — below that → "General".
 */

export const REFINED_TOPICS = {
  "AI & LLMs": [
    "ollama", "llm", "llama", "mistral", "gpt", "chatgpt", "claude",
    "inference", "rag", "embedding", "embeddings", "vector", "langchain",
    "transformer", "token", "tokens", "prompt", "fine-tune", "finetune",
    "lora", "qlora", "gguf", "ggml", "model", "ai model", "openai",
    "anthropic", "hugging face", "huggingface", "agent", "agents",
    "yolo", "stable diffusion", "comfyui", "neural", "machine learning",
    "deep learning", "nlp", "ai", "artificial intelligence",
    "whisper", "tts", "speech recognition", "copilot", "cursor",
    "context window", "quantize", "quantization", "mlx", "vllm",
    "kobold", "text generation",
    "gemini", "gemma", "phi-3", "phi3", "phi 3", "groq", "perplexity",
    "chatbot", "classification", "training data", "dataset",
    "object detection", "computer vision", "ocr",
    "tensorflow", "pytorch", "keras", "scikit",
    "mcp server", "bounding box", "qwen", "duke 3d",
  ],
  "GPU & Compute": [
    "gpu", "rtx", "nvidia", "cuda", "vram", "tok/s", "tokens per second",
    "benchmark", "psu", "power supply", "watt", "tdp", "amd", "radeon",
    "mac vs pc", "mac studio", "mac pro", "m1", "m2", "m3", "m4",
    "apple silicon", "unified memory", "egpu", "compute", "overclock",
    "framerate", "fps", "geforce", "tensor core", "rocm",
    "cpu", "ram", "ddr4", "ddr5", "motherboard", "pc build",
    "cooling", "heatsink", "thermal", "clock speed", "ghz",
    "n100", "9800x3d", "7600x", "mac mini", "studi",
  ],
  "Programming & Code": [
    "code", "function", "bug", "debug", "api", "database", "sql",
    "python", "javascript", "typescript", "react", "node", "nodejs",
    "git", "github", "deploy", "frontend", "backend", "algorithm",
    "class", "error", "stack", "npm", "brew", "bash", "shell", "script",
    "json", "yaml", "css", "html", "rust", "golang", "swift",
    "nextjs", "next.js", "vue", "svelte", "tailwind", "prisma",
    "postgres", "mongodb", "redis", "graphql", "rest api", "webhook",
    "regex", "lint", "webpack", "vite", "compiler", "parser",
    "async", "await", "promise", "callback", "refactor", "cron",
    "supabase", "firebase", "vercel", "lambda", "serverless",
    "variable", "loop", "array", "object", "string", "integer",
    "import", "export", "module", "package", "library", "framework",
    "endpoint", "middleware", "route", "handler", "query",
    "migration", "schema", "table", "index", "join",
    "test", "jest", "cypress", "playwright", "selenium",
    "docker", "dockerfile", "ci/cd", "pipeline", "github actions",
    "spreadsheet", "excel", "csv", "google sheets", "formula",
    "automation", "zapier", "make.com", "n8n", "airtable",
    "app", "webapp", "website", "page", "component",
    "ffmpeg", "symlink", "protobuf", "serialization", "grpc",
    "ipc", "tika", "tesseract", "service bus", "kafka",
    "microservice", "dashboard", "caching", "helm", "pdflatex",
    "yt-dlp", "public key", "openwrt", "azure", "diskann", "hnsw",
    "asin", "lookup", "onenote", "download",
  ],
  "Networking & Infra": [
    "unifi", "ubiquiti", "docker", "container", "proxmox", "k3s",
    "kubernetes", "home assistant", "homeassistant", "hass", "ssh",
    "vpn", "wireguard", "tailscale", "nginx", "reverse proxy", "traefik",
    "dns", "dhcp", "vlan", "subnet", "firewall", "router", "switch",
    "nas", "truenas", "synology", "plex", "jellyfin", "pihole",
    "portainer", "compose", "terraform", "ansible", "network",
    "ip address", "ssl", "certificate", "letsencrypt", "cloudflare",
    "mqtt", "zigbee", "z-wave", "esphome", "nodered", "node-red",
    "wifi", "ethernet", "access point", "mesh", "bandwidth",
    "port forward", "nat", "gateway", "bridge", "vswitch",
    "backup", "raid", "zfs", "samba", "nfs", "smb",
    "linux", "ubuntu", "debian", "proxmox", "vm", "virtual machine",
    "cloud key", "bluetooth", "lan speed", "internet speed",
  ],
  "Hardware & Electronics": [
    "arduino", "esp32", "esp8266", "raspberry pi", "rpi", "sensor",
    "pcb", "wiring", "solder", "circuit", "relay", "transistor",
    "resistor", "capacitor", "led", "servo", "stepper", "motor",
    "i2c", "spi", "uart", "gpio", "breadboard", "oscilloscope",
    "multimeter", "voltage", "ampere", "amp", "ohm", "diode",
    "microcontroller", "mcu", "firmware", "pinout", "schematic",
    "wire", "connector", "crimp", "terminal", "gauge",
    "camera", "security camera", "nvr", "surveillance",
    "charger", "pi5", "compatibility", "controller",
    "irfp", "mosfet", "inductor", "pressure",
  ],
  "3D Printing & CAD": [
    "3d print", "stl", "filament", "pla", "petg", "abs", "tpu",
    "slicer", "slicing", "cura", "prusaslicer", "bambu", "orca",
    "nozzle", "bed level", "layer height", "infill", "support",
    "modeling", "cad", "fusion 360", "onshape", "tinkercad",
    "openscad", "blender", "ender", "prusa", "voron", "extruder",
    "hotend", "retraction", "stringing", "gcode",
    "resin", "sla", "fdm", "enclosure", "print bed",
    "diorama", "miniature", "figurine", "prototype",
    "laser cut", "cnc", "router", "engraver",
  ],
  "Solar & Energy": [
    "solar", "panel", "photovoltaic", "inverter", "mppt",
    "battery", "batteries", "lifepo4", "lithium", "charge controller",
    "watt-hour", "kwh", "amp-hour", "ah", "bms", "off-grid",
    "grid-tie", "net meter", "enphase", "micro-inverter",
    "awg", "mc4", "combiner", "disconnect", "breaker",
    "energy storage", "powerwall", "solar generator", "jackery",
    "bluetti", "ecoflow", "renogy", "victron",
    "wind turbine", "generator", "transfer switch", "ups",
    "charging time", "rate change", "pse", "utility",
  ],
  "Animals & Livestock": [
    "duck", "ducks", "chicken", "chickens", "poultry", "rooster",
    "goat", "goats", "sheep", "cattle", "cow", "pig", "pigs",
    "fish", "aquarium", "pond", "bee", "bees", "beekeeping", "hive",
    "egg", "eggs", "incubat", "brood", "hatch", "coop", "flock",
    "feed", "livestock", "animal", "pet", "dog", "cat", "horse",
    "veterinar", "deworm", "vaccin", "breed", "chick",
    "turkey", "quail", "rabbit", "hutch", "pasture", "grazing",
    "waterer", "feeder", "nesting", "brooder", "predator",
    "midge", "fly trap", "insect trap",
    "nightcrawler", "worm", "gecko", "crested gecko",
    "cichlid", "loach", "isopod", "reptile", "terrarium",
    "tank", "gallon", "filter", "marlin", "pullet",
  ],
  "Gardening & Outdoors": [
    "garden", "gardening", "plant", "plants", "seed", "seedling",
    "ipm", "fertilizer", "compost", "mulch", "soil", "raised bed",
    "corn", "tomato", "pepper", "squash", "herb", "vegetable",
    "fruit", "tree", "prune", "pruning", "weed", "irrigation",
    "drip", "sprinkler", "zone", "perennial", "annual", "native",
    "pollinator", "pest", "insect", "fungus", "blight",
    "hiking", "camping", "fishing", "hunting", "trail", "outdoor",
    "kayak", "canoe", "tent", "backpack", "wilderness",
    "greenhouse", "hoop house", "cold frame", "transplant",
    "harvest", "crop", "yield", "grow", "growing",
    "flower", "bloom", "landscape", "yard", "orchard",
    "mushroom", "fungi", "spore", "mycelium",
    "wildlife", "bird", "birding", "feeder",
    "park", "nature", "river", "lake", "creek", "mountain",
    "hike", "hikes", "falls", "waterfall",
    "snorkel", "surfing", "beach", "coaster",
    "adventure", "activities", "fun activities",
    "seaworld", "san diego", "seattle", "redmond",
  ],
  "Food & Cooking": [
    "recipe", "cook", "cooking", "grill", "grilling", "smoke",
    "smoker", "bbq", "barbecue", "bake", "baking", "bread",
    "ferment", "fermentation", "sourdough", "kimchi", "sauerkraut",
    "sous vide", "instant pot", "slow cooker", "cast iron",
    "marinade", "rub", "seasoning", "spice", "sauce", "broth",
    "pickle", "preserve", "canning", "dehydrat",
    "meal prep", "dinner", "breakfast", "lunch", "snack",
    "beef", "pork", "chicken breast", "thigh", "steak",
    "cheese", "butter", "cream", "milk", "yogurt",
    "rice", "pasta", "noodle", "soup", "stew", "chili",
    "dessert", "cake", "cookie", "pie", "chocolate",
    "coffee", "tea", "beer", "wine", "whiskey", "cocktail",
    "leftover", "food safety", "temperature", "refrigerat",
    "ingredient", "substitute", "flour", "sugar", "salt",
    "oven", "stovetop", "air fryer", "skillet", "dutch oven",
    "flank", "bottom round", "ribeye", "roast", "ham", "glaze",
    "frittata", "wheat berries", "einkorn", "reheat",
    "caffeine", "candy",
  ],
  "Home & Property": [
    "appliance", "repair", "hvac", "plumbing", "electrical",
    "garage", "shed", "barn", "fence", "deck", "patio",
    "roof", "gutter", "insulation", "drywall", "paint",
    "cabinet", "countertop", "flooring", "tile", "concrete",
    "foundation", "septic", "well", "water heater", "furnace",
    "air condition", "thermostat", "dehumidif", "ventilation",
    "renovation", "remodel", "contractor", "permit", "inspection",
    "property", "acre", "land", "mortgage", "real estate",
    "mow", "lawn", "tractor", "mower", "chainsaw",
    "house", "home improvement", "room", "closet", "storage",
    "door", "window", "lock", "hinge", "screw", "bolt",
    "pipe", "faucet", "drain", "toilet", "shower",
    "car", "truck", "vehicle", "oil change", "tire", "brake",
    "trailer", "atv", "utv", "mileage", "mpg",
    "clean", "cleaning", "organize", "declutter",
    "furniture", "shelf", "table", "chair", "desk",
    "warranty", "replacement", "install", "mount",
    "ice maker", "hrv", "dishwasher", "washer", "dryer",
    "projector", "tv", "epson", "hisense", "monitor",
    "driveway", "gravel", "pea gravel", "lava rock",
  ],
  "Health & Fitness": [
    "running", "5k", "10k", "marathon", "half marathon",
    "training plan", "pace", "splits", "vo2",
    "workout", "exercise", "strength", "lift",
    "injury", "recovery", "stretch", "flexibility", "mobility",
    "calorie", "protein", "macro", "diet", "nutrition",
    "heart rate", "blood pressure", "cholesterol",
    "physical therapy", "knee pain", "back pain", "shoulder pain",
    "strain", "sprain", "cramp", "tendon", "muscle",
    "inflammation", "swelling", "fracture",
    "diagnosis", "symptom", "rash", "hives",
    "medical", "doctor", "urgent care",
    "medication", "ibuprofen", "tylenol", "antibiotic",
    "vitamin", "supplement", "magnesium",
    "yoga", "pilates", "cycling",
    "triathlon", "relay race",
    "garmin", "strava", "fitbit",
    "calf strain", "hamstring", "achilles", "plantar",
    "myocarditis", "pericarditis", "cardiologist",
    "run stats", "mile time", "lap breakdown", "1600m",
    "nordictrack", "treadmill", "elliptical",
    "cough", "flu", "cold", "fever", "sore throat",
    "amino", "nac", "efficacy",
    "hoka", "asics", "brooks", "saucony",
    "double chin", "weight loss",
  ],
  "Work & Leadership": [
    "perf review", "performance review", "feedback", "1:1", "one-on-one",
    "org design", "organization", "offsite", "strategy", "team",
    "leadership", "manager", "director", "vp", "executive",
    "hiring", "interview", "candidate", "onboarding", "retention",
    "okr", "kpi", "roadmap", "quarterly", "annual review",
    "promotion", "compensation", "salary", "bonus", "equity",
    "meeting", "agenda", "standup", "retrospective", "sprint",
    "stakeholder", "cross-functional", "alignment", "priority",
    "business", "company", "startup", "enterprise", "revenue",
    "customer", "client", "vendor", "contract", "sow",
    "project management", "scrum", "agile", "kanban", "jira",
    "budget", "forecast", "planning", "goal", "objective",
    "tax", "irs", "401k", "ira", "investment", "stock",
    "finance", "financial", "accounting", "expense", "income",
    "legal", "trademark", "patent", "copyright", "liability",
    "insurance", "mortgage", "loan", "credit", "debit",
    "school", "education", "iep", "college", "university",
    "career", "job", "profession", "industry", "sector",
  ],
  "Image Generation": [
    "dall-e", "dalle", "ghibli", "ghibli style", "coloring page",
    "illustration", "generate image", "image generation", "create image",
    "art style", "cartoon", "anime", "pixel art", "watercolor",
    "portrait", "logo design", "icon", "avatar",
    "midjourney", "stable diffusion", "controlnet", "img2img",
    "inpaint", "upscale", "dreambooth",
    "draw", "sketch", "painting", "artwork", "graphic",
    "color palette", "design", "mockup", "wireframe",
    "photo", "photograph", "edit photo", "photoshop",
    "svg", "vector art", "clip art", "sticker",
    "airbrush", "craft", "foam", "glue",
  ],
  "Writing & Content": [
    "write", "essay", "blog", "article", "draft", "edit",
    "grammar", "story", "poem", "creative writing", "content",
    "copy", "proofread", "email", "letter", "report",
    "summarize", "rewrite", "tone", "outline", "thesis",
    "resume", "cover letter", "bio", "tagline",
    "headline", "caption", "song", "lyric", "verse",
    "presentation", "slide", "pitch deck",
    "book", "chapter", "novel", "fiction", "nonfiction",
    "recap", "synopsis",
    "translate", "translation", "spanish", "french",
    "naming", "slogan", "motto",
    "travel", "flight", "hotel", "vacation", "trip",
    "destination", "itinerary", "reservation", "booking",
    "music", "guitar", "piano", "drum", "instrument",
    "chord", "tuning", "melody", "rhythm", "band",
    "movie", "tv show", "film", "documentary",
    "board game", "puzzle", "trivia",
    "gift", "birthday", "holiday", "christmas", "party",
    "relationship", "advice", "personal", "family",
    "shopping", "brand", "alternative",
    "clothing", "shoes", "hoodie", "jacket",
    "math", "calculate", "convert", "unit",
    "history", "geography", "weather",
    "bowling", "tattoo", "baseball", "basketball",
    "coin", "penny", "value", "price",
    "fursuit", "costume", "cosplay",
    "kids", "elf", "fun",
    "ribbon", "celebration", "poster",
    "iphone", "kindle", "gopro", "insta360",
    "boot", "crocs", "dr martens", "size",
    "gun", "shooting", "range",
    "español", "hablar",
    "robot", "name idea",
    "speed", "fast charge", "usb",
  ],
};

/**
 * Categorize a conversation using refined 15-topic system.
 *
 * @param {string} title — conversation title
 * @param {string} body — concatenated user messages (or first N)
 * @returns {string} topic name, or "General" if below threshold
 */
export function categorizeRefined(title, body = "") {
  const lowerTitle = (title || "").toLowerCase();
  const lowerBody = (body || "").toLowerCase();

  let bestTopic = "General";
  let bestScore = 0;

  for (const [topic, keywords] of Object.entries(REFINED_TOPICS)) {
    let score = 0;
    for (const kw of keywords) {
      // Title matches weighted 3x
      if (lowerTitle.includes(kw)) score += 3;
      // Body matches weighted 1x
      if (lowerBody.includes(kw)) score += 1;
    }
    if (score > bestScore) {
      bestScore = score;
      bestTopic = topic;
    }
  }

  // Minimum score threshold — below 2 falls to "General"
  return bestScore >= 2 ? bestTopic : "General";
}
